//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeriesAndFilms.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERIES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SERIES()
        {
            this.GENRES = new HashSet<GENRES>();
        }
    
        public int IDSeries { get; set; }
        public string SeriesName { get; set; }
        public string Description { get; set; }
        public decimal Rating { get; set; }
        public int Date { get; set; }
        public byte[] PhotoPath { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GENRES> GENRES { get; set; }
    }
}
